### ISSUE TITLE
Case rule places light in invalid position

### ISSUE THREAD

**Issue by Gerzer** [Bram-Hub/Legup#33] opened 2021-09-18 20:58 UTC
![Light Up - Case Rule (why not like bottom branch)](https://user-images.githubusercontent.com/5963974/135195259-2e2cc087-995b-4b84-873f-f37d5d0b3492.png)

The case rule in this puzzle file places a bulb in one of its branches in a square that's already illuminated by another light, which breaks the rules of Light Up. The relevant square is *not* manually confirmed to be empty when the case rule is applied, so it's not explicitly clear how LEGUP should handle the scenario. There are a few options:
1.	Refuse to apply a case rule in a situation in which it would produce one or more branches that are immediately invalid
2. Modify the existing case rules to permit the creation of branches that are immediately invalid as long as the correct contradiction rule (in this case, "Bulbs in Path") is subsequently applied
3. Avoid generating branches that lead to scenarios like this

Personally, I'm leaning towards the second option. What do other people think?

[Light Up - Case Rule (why not like bottom branch).zip](https://github.com/Bram-Hub/Legup/files/7190634/Light.Up.-.Case.Rule.why.not.like.bottom.branch.zip)

**Comment by Bram28** [comment] 2021-09-28 19:51
The issue here isn't that the correct solution isn't accepted: this proof is rejected because of the branches (as you can see by the red transitions).   But, that's where the issue is (or at least: one can argue that there is an issue) The bottom branch places a lightbulb in a lit cell. And sure, there cannot be a lightbulb ... but that's what the contradiction rule is for. So, I would say that if the user indicates that, *relative to the number 1", one of the options is to place a lightbulb next to the 1, then that should be ok.

Now, if you apply the case rule automatically, then that branch does not get generated ... and I think that makes sense as well in order to cut down the number of possible branches. But again, if the user adds that branch to indicate that relative to the 1, there is another option, then that should check out ok as well. .... I am wondering though: does the branching not check out because the automated case rule does not generate that branch?

**Comment by Gerzer** [comment] 2021-09-29 02:44
> contradiction rule is for. So, I would say that if the user indicates that, *relative to the number 1", one of the options is to place a lightbulb next to the 1, then that should be ok.
> 
> Now, if you apply the case rule automatically, then that branch does not get generated ... and I think that makes sense as well in order to cut down the number of possible branches. But again, if the user adds that branch to indicate that relative to the 1, there is another option, then that should check out ok as well. .... I am wondering though: does the branching not check out because the automated case rule does not generate that branch?

Ah, I see. I'll update this issue with the correct description of the problem soon. Thanks for the clarification!

**Comment by Gerzer** [comment] 2021-09-29 02:45
> The issue here isn't that the correct solution isn't accepted: this proof is rejected because of the branches (as you can see by the red transitions).   But, that's where the issue is (or at least: one can argue that there is an issue) The bottom branch places a lightbulb in a lit cell. And sure, there cannot be a lightbulb ... but that's what the contradiction rule is for. So, I would say that if the user indicates that, *relative to the number 1", one of the options is to place a lightbulb next to the 1, then that should be ok.
> 
> 
> 
> Now, if you apply the case rule automatically, then that branch does not get generated ... and I think that makes sense as well in order to cut down the number of possible branches. But again, if the user adds that branch to indicate that relative to the 1, there is another option, then that should check out ok as well. .... I am wondering though: does the branching not check out because the automated case rule does not generate that branch?

Ah, I see. I'll update this issue with the correct description of the problem soon. Thanks for the clarification!

**Comment by Gerzer** [comment] 2021-09-29 02:54
@Bram28 What do you think of the revised problem description? Is it accurate?

**Comment by Bram28** [comment] 2021-09-29 14:12
Yes, that looks good, thanks! 

And I lean towards the second option as well, though I wouldn't require that the user has to immediately apply some contradiction rule ... it just becomes another branch, and whatever else happens in that branch is up to the user ... the contradiction could be pointed out much, much later. 

Also, here is one more argument to allow the user (when manually adding case branches) to indicate the 'offending' branch: it's just the very fact that the square, though lit, is still modifiable. We make a difference between lit but still 'open' squares, and squares that are lit and empty (indeed, we have a rule to make lit squares into lit and empty squares). And so, if the focus is on the 1, then the user should be able to add this branch, even if the automated routine considers it empty and doesn't add it (because in the solution, we also accept lit squares as implicitly empty).

**Comment by cjreed121** [comment] 2022-05-29 18:55
Seems to be fixed now upon testing.

**Closed by cjreed121** 2022-05-29 18:55 UTC
Labels: bug, light up
