### ISSUE TITLE
[ENHANCEMENT] Flag Files as solved or not

### ISSUE THREAD

**Issue by shadowluigi27** [Bram-Hub/Legup#302] opened 2022-09-30 21:37 UTC
### Describe the current behavior of what you're trying to improve. If your enhancement request related to a problem, please also describe the problem.

The Batch Grader is extremely slow due to it having to open the files and check each file individually using the check function. We want to improve the speed by making so that the Batch Grader only needs to read the xml flag of a puzzle to determine if it is correct.

### Describe the improvement you'd like

Each puzzle file now has a xml flag that is set to false initially, and only when the check proof button is clicked is it ever set to true (if the puzzle is solved). Any changes made immediately sets the flag to false, even if it was true before).

There could also be a indicator in the top left that shows the user if the puzzle is solved or not.

**Comment by wei-jun7** [comment] 2022-10-30 22:05
It is done using the batch grade to check it is been proof or not.

**Comment by charlestian23** [comment] 2023-01-17 15:54
Duplicate of #395

**Closed by charlestian23** 2023-01-17 15:54 UTC
Labels: duplicate, enhancement
