### ISSUE TITLE
Interacting With Previous State Prevents Placement

### ISSUE THREAD

**Issue by MMosley502** [Bram-Hub/Legup#97] opened 2022-04-18 21:53 UTC
### Current Behavior
If a previous state in the tree is accessed after a case rule has been used part or all of the current board will become unmodifiable. Image of unmodifiable state included: 
![image](https://user-images.githubusercontent.com/74743867/163882996-5ce0e3f0-714e-4b2b-81c7-618ea32bdf88.png)

### Expected Behavior 
The current state should still be modifiable.

### Steps to Reproduce
Open a nurikabe a file. Create at least one valid state then use case rule. Once case rule has been used select a state before case rule and change and revert a tile in it. The current state after the case rule will now be unmodifiable.
Attached files with unmodifiable states:
[CaseRuleError.zip](https://github.com/Bram-Hub/Legup/files/8508376/CaseRuleError.zip)

**Comment by cjreed121** [comment] 2022-05-28 20:05
Looking at your image, it appears you were selected on the blue circle in the TreePanel. If you want to make a change to the board you would do it on an arrow which can be assigned a rule. So this is actually expected behavior that you receive the unmodifiable state message. I'm closing this issue due to this.

**Comment by Bram28** [comment] 2022-06-06 15:19
No, this is a real and annoying bug: if you are on the transition you still cannot select squares at times ... and I think it indeed has to do with the case rule. I myself and several students have run into this.

**Comment by charlestian23** [comment] 2022-06-06 20:58
A separate occurrence of the same bug:

## Current Behavior
Modifying the previous transition of some node renders the node after that node unmodifiable.

## Expected Behavior
Modifying the previous transition of some node should not render that node unmodifiable.

## Steps to Reproduce
![2022-06-06_16-49-09_AdobeExpress](https://user-images.githubusercontent.com/46334090/172248031-c0c1433a-1ad8-4949-8511-03b64ec5ba8a.gif)

[unmodifiable_bug.zip](https://github.com/Bram-Hub/Legup/files/8847959/unmodifiable_bug.zip)

**Comment by charlestian23** [comment] 2022-06-06 21:03
I'm going to remove the Nurikabe label since this bug isn't related to something about Nurikabe, and I think it's moreso related how Legup in general deals with users modifying transitions.

**Comment by Bram28** [comment] 2022-06-09 19:17
And yes, it took me 10 second to reproduce something similar in Light-Up... this is a general LEGUP issue!

**Comment by cjreed121** [comment] 2022-06-09 19:18
Thanks for the steps. I was able to reproduce it with @charlestian23 steps. I think I have a fix for it though in #113.

**Closed** 2022-06-09 22:37 UTC
Labels: bug, priority
